### PR TITLE
chore(CI): Update master php testing versions and workflow templates

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by come-nc** [comment]
`nextcloud/ocp` dep was removed, was that on purpose?
If so, the update ocp workflow should be removed as well, or it will fail: https://github.com/nextcloud/impersonate/actions/runs/5634079483/job/15263647092

**Pull request merged**
