### PR TITLE
Move Impersonate-Button to Dropdown

### PR DESCRIPTION
**Pull request by prodingerd**
Addresses #4, #8 and #9

Signed-off-by: Dominik Prodinger <prodinger.d@outlook.com>

### CODE REVIEW

**Comment by MariusBluem** [comment]
The code change seems to be different from the #13 ..

**Comment by prodingerd** [comment]
@MariusBluem This PR and #13 result in the same impersonate.js file. #13 does change the indentation of some lines however, this is why the commits look different.

**Comment by MariusBluem** [comment]
@blizzz

**Comment by blizzz** [comment]
thanks @prodingerd! 🎉

**Pull request merged**
