### PR TITLE
Move Impersonate-Button Into Dropdown

### PR DESCRIPTION
**Pull request by prodingerd**
This pull request addresses #4, #8 and #9.

### CODE REVIEW

**Comment by prodingerd** [comment]
@MorrisJobke may someone please review this pull request?

**Comment by MorrisJobke** [comment]
@MariusBluem Could you try this PR, because there are linked issues from you? ;)

**Comment by MariusBluem** [comment]
I will. Thanks for the PR 💪

**Comment by blizzz** [comment]
@MariusBluem 🏓

**Comment by MariusBluem** [comment]
Works 👍

**Comment by MariusBluem** [comment]
Please check CI, merge, and release it - thanks 👍 @blizzz

**Comment by MariusBluem** [comment]
fixes #4, #8

**Comment by blizzz** [comment]
@prodingerd could you sign-off your commits?

**Comment by prodingerd** [comment]
@blizzz I'll open a new PR, I've messed up the commit history. Just to be clear, do you want me to sign-off my commits, or sign them with my PGP key?

**Comment by MariusBluem** [comment]
@prodingerd Only sign-off-by is needed - signed via PGP is optional :)

**Pull request closed without merging**
